In [1]:
#libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
#get the dataset from yahoo finance
df = pd.read_csv('downloads/ETH-USD.csv')
df

Date         Open         High          Low        Close  \
0    2019-12-08   148.743683   152.392929   148.313339   151.264725   
1    2019-12-09   151.224396   151.913940   147.621368   148.225174   
2    2019-12-10   148.179855   148.564468   144.907959   146.267044   
3    2019-12-11   146.320648   147.139206   143.045364   143.608002   
4    2019-12-12   143.615662   145.751648   141.436981   145.604004   
..          ...          ...          ...          ...          ...   
516  2021-05-07  3490.105225  3573.290039  3370.261963  3484.729004   
517  2021-05-08  3481.988037  3950.165039  3453.768555  3902.647705   
518  2021-05-09  3911.463135  3981.259033  3743.989014  3928.844727   
519  2021-05-10  3924.413330  4197.473145  3684.451660  3952.293945   
520  2021-05-11  3948.271973  4178.208984  3783.889404  4168.701172   

       Adj Close        Volume  
0     151.264725  6.441727e+09  
1     148.225174  6.744207e+09  
2     146.267044  6.859512e+09  
3     143.608002  7.037180e+09  
4     145.604004  7.890383e+09  
..           ...           ...  
516  3484.729004  3.960724e+10  
517  3902.647705  5.020849e+10  
518  3928.844727  5.056829e+10  
519  3952.293945  6.269179e+10  
520  4168.701172  5.267974e+10  

[521 rows x 7 columns]

In [3]:
df.dropna(inplace=True)

In [4]:
df.isna().any()

Date         False
Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [6]:
#create a column that is 'n' days into future
projection = 14 #14days

#prediction column
df['Prediction'] = df[['Close']].shift(-projection)#shift , shifts index by number of periods with opt time frequency
df

Date         Open         High          Low        Close  \
0    2019-12-08   148.743683   152.392929   148.313339   151.264725   
1    2019-12-09   151.224396   151.913940   147.621368   148.225174   
2    2019-12-10   148.179855   148.564468   144.907959   146.267044   
3    2019-12-11   146.320648   147.139206   143.045364   143.608002   
4    2019-12-12   143.615662   145.751648   141.436981   145.604004   
..          ...          ...          ...          ...          ...   
516  2021-05-07  3490.105225  3573.290039  3370.261963  3484.729004   
517  2021-05-08  3481.988037  3950.165039  3453.768555  3902.647705   
518  2021-05-09  3911.463135  3981.259033  3743.989014  3928.844727   
519  2021-05-10  3924.413330  4197.473145  3684.451660  3952.293945   
520  2021-05-11  3948.271973  4178.208984  3783.889404  4168.701172   

       Adj Close        Volume  Prediction  
0     151.264725  6.441727e+09  132.372513  
1     148.225174  6.744207e+09  128.614090  
2     146.267044  6.859512e+09  129.063889  
3     143.608002  7.037180e+09  126.454636  
4     145.604004  7.890383e+09  126.361221  
..           ...           ...         ...  
516  3484.729004  3.960724e+10         NaN  
517  3902.647705  5.020849e+10         NaN  
518  3928.844727  5.056829e+10         NaN  
519  3952.293945  6.269179e+10         NaN  
520  4168.701172  5.267974e+10         NaN  

[517 rows x 8 columns]

In [7]:
#independent variable
X = np.array(df[['Close']])

#removing last 14
X = X[:-projection]

X

array([[ 151.264725],
       [ 148.225174],
       [ 146.267044],
       [ 143.608002],
       [ 145.604004],
       [ 144.944748],
       [ 142.869232],
       [ 143.11499 ],
       [ 133.614029],
       [ 122.603889],
       [ 133.092194],
       [ 129.321136],
       [ 129.066055],
       [ 128.130951],
       [ 132.372513],
       [ 128.61409 ],
       [ 129.063889],
       [ 126.454636],
       [ 126.361221],
       [ 127.214607],
       [ 128.322708],
       [ 134.75798 ],
       [ 132.633484],
       [ 129.610855],
       [ 130.802002],
       [ 127.410179],
       [ 134.171707],
       [ 135.069366],
       [ 136.276779],
       [ 144.304153],
       [ 143.543991],
       [ 141.258133],
       [ 138.979202],
       [ 143.963776],
       [ 142.927109],
       [ 145.873932],
       [ 144.226593],
       [ 165.955353],
       [ 166.230682],
       [ 164.391006],
       [ 170.779953],
       [ 175.365677],
       [ 166.969849],
       [ 167.120514],
       [ 169.697159],
       [ 1

In [8]:
#dependent data
y = df['Prediction'].values
y = y[:-projection]
y

array([ 132.372513,  128.61409 ,  129.063889,  126.454636,  126.361221,
        127.214607,  128.322708,  134.75798 ,  132.633484,  129.610855,
        130.802002,  127.410179,  134.171707,  135.069366,  136.276779,
        144.304153,  143.543991,  141.258133,  138.979202,  143.963776,
        142.927109,  145.873932,  144.226593,  165.955353,  166.230682,
        164.391006,  170.779953,  175.365677,  166.969849,  167.120514,
        169.697159,  168.294159,  162.928558,  163.051178,  161.283936,
        168.077103,  170.930893,  176.370316,  175.050339,  184.690475,
        180.160172,  183.67395 ,  188.617538,  189.865067,  189.250595,
        204.23024 ,  212.339081,  222.726059,  223.146515,  228.578568,
        223.522705,  235.851196,  265.406128,  268.099243,  284.217499,
        264.728577,  259.894714,  266.363434,  281.94458 ,  259.763977,
        257.949463,  265.600616,  262.331726,  273.75415 ,  265.216431,
        247.817596,  225.680267,  226.753387,  226.760498,  219.

In [9]:
#85% train and 15% test splitting
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.15)

In [10]:
#modelling
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
#score testing
model.score(X_test,y_test)

0.9416287550579048

In [17]:
#setting last shifted rows to x_projection 
x_projection = np.array(df[['Close']][-projection:])
x_projection

array([[2746.380127],
       [2756.876953],
       [2773.207031],
       [2945.892822],
       [2952.056152],
       [3431.086182],
       [3253.629395],
       [3522.783203],
       [3490.880371],
       [3484.729004],
       [3902.647705],
       [3928.844727],
       [3952.293945],
       [4168.701172]])

In [18]:
#prediction
model.predict(x_projection)

array([3223.23912438, 3235.65683011, 3254.97525105, 3459.26189319,
       3466.55308943, 4033.24381567, 3823.31310318, 4141.7210471 ,
       4103.98011667, 4096.70307261, 4591.09932618, 4622.09030481,
       4649.83064163, 4905.83957834])

In [ ]:
#so from the above, 14 days from 2021-05-11, price/prediction will be 4905.83957834